// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPRYVOK3B5EGA4S9q-6nowrplRjmsvS_w',
    appId: '1:850474464882:web:bc1f4ebfa2f4787b0a34eb',
    messagingSenderId: '850474464882',
    projectId: 'bookly-5066c',
    authDomain: 'bookly-5066c.firebaseapp.com',
    storageBucket: 'bookly-5066c.appspot.com',
    measurementId: 'G-3G0DP29S6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCveAISY3Sblhhid7s07Aiqfxj4Be4ZiXI',
    appId: '1:850474464882:android:bf5e4ece4b03a8b40a34eb',
    messagingSenderId: '850474464882',
    projectId: 'bookly-5066c',
    storageBucket: 'bookly-5066c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8X5VnG9wTKEQCCQ__GjQwl1mdQ6oCVbE',
    appId: '1:850474464882:ios:bffb6ad42ff9bc030a34eb',
    messagingSenderId: '850474464882',
    projectId: 'bookly-5066c',
    storageBucket: 'bookly-5066c.appspot.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8X5VnG9wTKEQCCQ__GjQwl1mdQ6oCVbE',
    appId: '1:850474464882:ios:bffb6ad42ff9bc030a34eb',
    messagingSenderId: '850474464882',
    projectId: 'bookly-5066c',
    storageBucket: 'bookly-5066c.appspot.com',
    iosBundleId: 'com.example.bookly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPRYVOK3B5EGA4S9q-6nowrplRjmsvS_w',
    appId: '1:850474464882:web:a109132b6dcad6690a34eb',
    messagingSenderId: '850474464882',
    projectId: 'bookly-5066c',
    authDomain: 'bookly-5066c.firebaseapp.com',
    storageBucket: 'bookly-5066c.appspot.com',
    measurementId: 'G-DNV6XMJV2L',
  );
}
